---
- name: magnum user
  user: name=magnum comment=magnum shell=/bin/false system=yes
        home=/nonexistent createhome=no

- name: magnum config dir
  file: dest=/etc/magnum state=directory

- name: magnum log dir
  file: dest=/var/log/magnum state=directory mode=0755 owner=magnum
        group=magnum

# This patches a bug I found in magnum's 'newton-eol' branch, which is what package version '2017.2-bbc281' is based on.
# Without this, the call to the 'magnum-db-manage' later in this play will crash with a stack trace.
# The fix is to remove the last method argument in the file referenced by this task, which is shown by the following diff.
# Diff:
#   -options.set_defaults(cfg.CONF, _DEFAULT_SQL_CONNECTION, 'magnum.sqlite')
#   +options.set_defaults(cfg.CONF, _DEFAULT_SQL_CONNECTION)
- name: patch magnum bug
  lineinfile:
    dest: /opt/bbc/openstack-2017.2-bbc281/magnum/local/lib/python2.7/site-packages/magnum/db/__init__.py
    regexp: ^options.set_defaults
    line: options.set_defaults(cfg.CONF, _DEFAULT_SQL_CONNECTION)

- name: install magnum service
  upstart_service: name={{ item }} user=magnum cmd=/usr/local/bin/{{ item }}
                   config_dirs=/etc/magnum
  with_items:
    - magnum-api
    - magnum-conductor

- name: configure magnum
  template: src={{ item }} dest=/etc/magnum/ mode=0640
            owner=root group=magnum
  with_fileglob: ../templates/etc/magnum/*
  notify:
    - restart magnum services

- name: stop magnum service before db sync
  service: name={{ item }} state=stopped
  with_items:
    - magnum-api
    - magnum-conductor
  when: database_create.changed or force_sync|default('false')|bool

- name: sync magnum database
  command: magnum-db-manage upgrade
  when: database_create.changed or force_sync|default('false')|bool
  run_once: true
  changed_when: true
  notify: restart magnum services
  # we want this to always be changed so that it can notify the service restart

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify: restart magnum services
  when: code_has_changed | default('False') | bool and
        upgrade | default('False') | bool

- meta: flush_handlers

- name: restart magum services
  service: name={{ item }} state=started
  with_items:
    - magnum-api
    - magnum-conductor

# TODO:
#- include: monitoring.yml tags=monitoring,common

#- include: logging.yml
#  tags:
#    - logrotate
#    - logging
