---
- hosts: all:!vyatta-*
  tasks:
  - name: Patch CVE-2018-0737 CVE-2018-0732 
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
      cache_valid_time: 3600
    with_items:
      - openssl
    register: pkgupdate
    until: pkgupdate|succeeded
    retries: 5
    environment: "{{ env_vars }}"
  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
    when: "pkgupdate.changed and ('controller' in group_names or 'swiftnode' in group_names)"
  - name: restart apache
    service:
      name: apache2
      state: restarted
    when: "pkgupdate.changed and ('controller' in group_names)"
